### ISSUE TITLE
ELIC 

### ISSUE THREAD

**Issue by battlepeace** [VincentChandelier/ELiC-ReImplemetation#1]
On your github homepage, I saw your reproduction of the ELIC model, but I did not find your project code. If your project is open source, can you use your code? I want to learn and improve on this basis. Thank you very much for checking your email during your busy time. I wish you a smooth and fruitful research.

**Comment by VincentChandelier** [comment]
https://github.com/VincentChandelier/ELiC-ReImplemetation is available.
QVRF version (https://github.com/VincentChandelier/ELIC-QVRF) is recommended for use.
