### ISSUE TITLE
KeyError: 'gaussian_conditional._quantized_cdf'

### ISSUE THREAD

**Issue by LSJ047** [VincentChandelier/ELiC-ReImplemetation#13]
I hope this message finds you well. I am reaching out to seek your assistance with a matter related to my project. After training my model, I executed the updata.py script. However, when I tried to run it with the command python -m updata.py ..., I encountered an error. Consequently, I used python updata.py ... instead. Following this, when I attempted to run the Inference.py script, I faced a KeyError: 'gaussian_conditional._quantized_cdf'. Interestingly, when I utilize the points you provided, it works without any issues.
I would greatly appreciate it if you could guide me on resolving this error. Your expertise in this matter would be invaluable to me. Thank you for your time and assistance.
Best regards

**Comment by 2695108440** [comment]
Hello, I have encountered the same problem as you. How did you solve it?
