### ISSUE TITLE
Would you please share your pretrained model?

### ISSUE THREAD

**Issue by HannibalWangLecter** [VincentChandelier/ELiC-ReImplemetation#2]
Hi, I am a researcher in the field of image compression and I fork and star your repo, I am going to deeply study your code and try them on my GPU server. right now I am stuck in the process of acquiring your pre-trained model in ImageNet.
I am a researcher whose main study direction is image compression in china and work with MPEG institution, I am going to propose a proposal this year. My email is 441301158@qq.com, my LinkedIn link is https://www.linkedin.cn/incareer/in/ACoAABep-X4BjAR9eJ8YG2PwaODFNiGOSWGauaE, please kindly share your Pretrained4000epoch_checkpoint.pth.tar or checkpoint.pth.tar. Thank you very much!

**Comment by VincentChandelier** [comment]
The checkpoint is available in the ReadMe file.
And, The QVRF version (https://github.com/VincentChandelier/ELIC-QVRF) is recommended to train a variable rate model to save training costs.

**Comment by HannibalWangLecter** [comment]
> The checkpoint is available in the ReadMe file. And, The QVRF version (https://github.com/VincentChandelier/ELIC-QVRF) is recommended to train a variable rate model to save training costs.

Before this comment, I reimplemented your method and tried to train from start using OpenImages selected 70000 pictures. It's very weird in the part of caculating Biterate part, it seems your original code is not right, i correct it.

Thank you very much for your contribution.

**Comment by VincentChandelier** [comment]
Can you point out the wrong code in this repo?
It may contribute to others.

**Comment by HannibalWangLecter** [comment]
> Can you point out the wrong code in this repo? It may contribute to others.

I'm not quite sure this is right, this is my edition.

def get_list_bytes_size_bits(lst):  
    '''
    计算一个多层list占据的空间bit数,最里面的元素类型是bytes。  
    '''
    size_bits = 0  
    for item in lst:  
        if isinstance(item, list):  
            size_bits += get_list_bytes_size_bits(item)  
        else:  
            size_bits += len(item)*8   #AttributeError: 'bytes' object has no attribute 'bit_length'，bytes没有bit_length()方法，解决方法：size += len(item)*8
    return size_bits


    for i in range(B):
        start = time.time()
        out_enc = model.compress(x_padded[i:i+1, :, :, :])


        enc_time += time.time() - start

        start = time.time()
        out_dec = model.decompress(out_enc["strings"], out_enc["shape"])
        dec_time += time.time() - start


        bits_all += get_list_bytes_size_bits(out_enc["strings"]) #计算编码后的bit数

        #下面这三行是ELIC计算Bpp的方法,先注释掉
        # for s in out_enc["strings"]:
        #     for j in s:
        #         bpp += len(j)

        Rec[i:i+1, :, :, :] = out_dec["x_hat"]

    Rec = img_window_reverse(Rec, p, height, width)  # 反变换(N,C,Hpatch,Wpatch)->（1,C,H,W)
    Rec = F.pad(
        Rec, (-padding_left, -padding_right, -padding_top, -padding_bottom)
    )

    num_pixels = x.size(0) * x.size(2) * x.size(3)

    #bpp *= 8.0 / num_pixels  # ELIC的计算bpp的方法，算出来结果比正常值低很多，是因为
    #bpp = sum(len(s[0]) for s in out_enc["strings"]) * 8.0 / num_pixels #CompressAI 官方计算bpp的方法
    
    bpp = bits_all / num_pixels #WH写的计算bpp的方法,汇总所有的patch的bit数，然后除以像素数

**Comment by VincentChandelier** [comment]
The img_window_reverse function is used for super-high-resolution plenoptic images to compress each patch sequentially.

Full-resolution images are suitable for ELIC inference. Thus, the inference code of CompressAI (https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/utils/eval_model/__main__.py)  is suitable for the ELIC inference stage. And, the ELIC-QVRF ( https://github.com/VincentChandelier/ELIC-QVRF/blob/main/Inference.py ) is also can be used for reference to calculate bit consumption.

I test the following code  for an image patch
```
bpp = 0
for s in out_enc["strings"]:
    for j in s:
        bpp += len(j)
```
equals to 
```
bpp = sum(len(s[0]) for s in out_enc["strings"])
```

Maybe your codes are right. You can use your code to test the provided checkpoint and compare the results.

It is great to share your results.

**Comment by HannibalWangLecter** [comment]
> The img_window_reverse function is used for super-high-resolution plenoptic images to compress each patch sequentially.
> 
> Full-resolution images are suitable for ELIC inference. Thus, the inference code of CompressAI (https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/utils/eval_model/__main__.py) is suitable for the ELIC inference stage. And, the ELIC-QVRF ( https://github.com/VincentChandelier/ELIC-QVRF/blob/main/Inference.py ) is also can be used for reference to calculate bit consumption.
> 
> I test the following code for an image patch
> 
> ```
> bpp = 0
> for s in out_enc["strings"]:
>     for j in s:
>         bpp += len(j)
> ```
> 
> equals to
> 
> ```
> bpp = sum(len(s[0]) for s in out_enc["strings"])
> ```
> 
> Maybe your codes are right. You can use your code to test the provided checkpoint and compare the results.
> 
> It is great to share your results.

OK, Thank you very much.
