### ISSUE TITLE
[model to .onnx] only forward function

### ISSUE THREAD

**Issue by YI-MAX-YAN** [VincentChandelier/ELiC-ReImplemetation#4]
Hi, I  want to discuss with you that model to .onnx only forward function, how can we calculate the bpp and PSNR?

**Comment by VincentChandelier** [comment]
BPP (bits per pixel) is the number of bits consumed by image compression divided by the total number of pixels in the image.
PSNR (peak signal-to-noise ratio) is a measure of the similarity between the reconstructed image and the original image.
