### ISSUE TITLE
support_slices = torch.concat([y_hat_slices[0], y_hat_slices[slice_index-1]], dim=1)

### ISSUE THREAD

**Issue by DuBianJun-007** [VincentChandelier/ELiC-ReImplemetation#6]
support_slices = torch.concat([y_hat_slices[0], y_hat_slices[slice_index-1]], dim=1)
Here, only the first slice and the current slice are used for calculation, while the paper shows that all previous slices are used together with the current slice for calculation. I don't understand, can you explain?

**Comment by VincentChandelier** [comment]
Yes, What you said is consistent with the paper
